### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by stevenvachon**
* added separate tests for `.add()`
* added tests for adding/removing multiple classes
* all HTML tests now have SVG variants for better coverage
* clarified test titles for `.toggle()` as to differentiate them from the other methods
* switched to current latest 2.x version of QUnit

### CODE REVIEW

**Comment by stevenvachon** [comment]
If you set up a free BrowserStack account for this project, I can wire up the test suite.

**Comment by stevenvachon** [comment]
@beck

**Comment by beck** [comment]
Not yet willing to give up on upstream: https://github.com/eligrey/classList.js/issues/63

**Comment by stevenvachon** [comment]
That guy takes years to hear back from. I've given up on him.

**Comment by beck** [comment]
I've rewritten all the tests and implemented e2e scaffolding and a bit of CI so the polyfill gets tested across browsers.

Closing this in favor of: https://github.com/eligrey/classList.js/pull/69

**Pull request closed without merging**
